### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by cristiandley** [apollostack/meteor-integration#28]
Hi

How do i add CORS to the apollo instance ?

I'v been working in test-apps and now i want to move my Apollo-Express to Meteor/Apollo. Im trying to obtain the "app" or "graphqlServer" instance to call the .use() method. Maybe is it ready ? or im confused... 

Thanks

**Comment by jangerhofer** [comment]
Assuming you want to run the Apollo Server inside a Meteor instance, you will want to bind the Express server to Meteor like [this.](https://github.com/apollostack/meteor-integration/blob/master/main-server.js#L64)

**Comment by cristiandley** [comment]
By mistake i started this issue here, its originally posted here: https://github.com/apollostack/apollo-client/issues/529

**Comment by cristiandley** [comment]
Nope, in fact i moved into `meteor-integration` because i was using purely graphql server and well... is there a way to import the graphQlServer const ? 

so i can make something like `graphQLServer.use('*', cors());`

**Comment by jangerhofer** [comment]
Ah, now that I have seen your snippet from [here](https://github.com/apollostack/apollo-client/issues/529), I see your problem.

Because this package exports only `createApolloServer()` you won't be able to modify the Express server inside, except using the arguments `createApolloServer()` takes.

Your best bet is to forgo this package and create the server using [`apolloExpress`](http://docs.apollostack.com/apollo-server/setup.html#apolloExpress) and `graphQLServer.use('*', cors());` like your snippet indicated.

**Comment by cristiandley** [comment]
@jangerhofer thanks !!! i will continue ussing `apolloExpress`

i go sad :cry:  lol. It could be a feature for the future! :smile:

**Comment by Kunal1985** [comment]
Here is what worked for me
Just replace the line
const client = new ApolloClient(meteorClientConfig());
with below lines
const networkInterface = createNetworkInterface('http://192.168.1.52:3000/graphql');
const client = new ApolloClient(networkInterface);

and use the below import
import ApolloClient, { createNetworkInterface } from 'apollo-client';

The main issue is the use of meteorClientConfig() instead of networkInterface which gives you the flexibility of using your own custom configurations. Using meteorClientConfig() defaults the Apollo Client to use default URL for GraphQL server i.e 'http://localhost:3000/graphql'.

NOTE: 192.168.1.52 is my remote IP address.

**Comment by cristiandley** [comment]
@Kunal1985 cool solution Kunal.

I just decided to do it all by myself, is not so much code you get wrapped... and im just testing migrating an app by the moment. I would be cool if we could extend meteorClientConfig().

**Comment by nicolaslopezj** [comment]
#32 fixes this

**Comment by zvictor** [comment]
just sharing my code as it might help someone else in the future:

```js
import { createApolloServer } from 'meteor/apollo';
import cors from 'cors';
import schema from './apolloSchema';

createApolloServer({
  schema,
  context: {},
  formatError(error) {
    console.error(error.stack);

    return error;
  },
}, {
  configServer(app) {
    if (Meteor.isDevelopment) {
      // Enable unrestricted cors only in development
      // @see https://github.com/expressjs/cors for customization
      app.use(cors());
    }
  },
});
```
