### ISSUE TITLE
Remove mongo / minimongo from client?

### ISSUE THREAD

**Issue by Torsten85** [apollostack/meteor-integration#51]
Hey,
One question thats bothering me: Is it possible to completely remove mongo and minimongo from the client?

This package uses `accounts-base` which has a dependency to `mongo`, so I guess thats the problem here right?

**Comment by lorensr** [comment]
Ah, interesting. This package should probably be separated into `apollo` and `apollo-meteor-accounts`. For now I'd fork this and take out the accounts stuff from client:

https://github.com/apollostack/meteor-integration/blob/master/main-client.js

and take out this line:

https://github.com/apollostack/meteor-integration/blob/master/package.js#L12

and add:

`api.use('accounts-base', 'server');`

(or also take out `Accounts` from server side)

**Comment by Torsten85** [comment]
thanks for your answer. I could strip out everything from `accounts-base` ect. but I like to still have the possibility to use the meteor authentication. I simply don't need the Accounts.users collection or any other mongo collection on the client. 

but I guess that would need a different accounts package.

**Comment by NitroBAY** [comment]
> This package should probably be separated into apollo and apollo-meteor-accounts

Yes it should. I don't see why this package should depend on accounts-base as accounts-base needs mongo and if we're using apollo we're not using mongo.

**Comment by xavcz** [comment]
@nitrobay 👋,  the package depends on `accounts-base` at the moment because it adds the current user to the resolvers context for you, and create a middleware for the network interface to grab the login token and pass it with every request.

This package has been made to integrate the Apollo tools painlessly in a Meteor app (black box package). If you are not using Meteor Accounts system, there is almost no value in this package: you should instantiate your own server (~20 lines of code) and your own client (~10 lines of code).

To get rid of `accounts-base` while not breaking people apps that rely on it, we would have two atmosphere packages:
- a black box creation of the server and the client with some predefined options (~whats done now)
- a package depending on accounts-base that export a network interface middleware and a function to lookup the current user on the server and add her to the context (these functions exist now)

Do you think you could make a pull request to extract the accounts related code into a separate atmosphere package? 🙏

**Comment by NitroBAY** [comment]
Okay I'll make a PR if whenever I could. Thanks a lot about the informations, it's now much clearer
